export const restaurantList = [
  {
    id: 1,
    name: "Foodworld",
    logo: "./img/icon/foodworldlogo.png",
    image: "./img/foodworld.png",
    isOpen: false,
    discount: 20,
    delivery: "fast",
    review: 46,
  },
  {
    id: 2,
    name: "Pizzahub",
    logo: "./img/icon/pizzahublogo.png",
    image: "./img/pizzahurt.png",
    isOpen: false,
    discount: 15,
    delivery: "fast",
    review: 40,
  },
  {
    id: 3,
    name: "Donuts hut",
    logo: "./img/icon/donnuthutlogo.png",
    image: "./img/donust-hut-1.png",
    isOpen: true,
    discount: 10,
    delivery: "fast",
    review: 20,
  },
  {
    id: 4,
    name: "Donuts hut",
    logo: "./img/icon/donnuthutlogogreen.png",
    image: "./img/donust-hut.png",
    isOpen: true,
    discount: 15,
    delivery: "fast",
    review: 50,
  },
  {
    id: 5,
    name: "Ruby Tuesday",
    logo: "./img/icon/rubylogo.png",
    image: "./img/ruby-tuesday.png",
    isOpen: true,
    discount: 20,
    delivery: "fast",
    review: 46,
  },
  {
    id: 6,
    name: "Kuakata Fried Chicken",
    logo: "./img/icon/kfclogo.png",
    image: "./img/kuakate-fried-chicken.png",
    isOpen: true,
    discount: 10,
    delivery: "fast",
    review: 26,
  },
  {
    id: 7,
    name: "Red Square",
    logo: "./img/icon/redsquare.png",
    image: "./img/red-square.png",
    isOpen: true,
    discount: 10,
    delivery: "fast",
    review: 45,
  },
  {
    id: 8,
    name: "Taco Bell",
    logo: "./img/icon/tacologo.png",
    image: "./img/taco-bell.png",
    isOpen: true,
    discount: 10,
    delivery: "fast",
    review: 35,
  },
];
